version: '3.7'

services:
  pagleve-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: pagleve-server
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn dev:server
